### ISSUE TITLE
Fixed in latest development build, use exe

### ISSUE THREAD

**Issue by KalpanaChetan** [prateekmedia/pstube#87]
Fixed in latest development build, use exe

_Originally posted by @prateekmedia in https://github.com/prateekmedia/pstube/issues/79#issuecomment-1371996753_

App open but nothing show in first time 

Why this happens in nightly build

**Comment by prateekmedia** [comment]
Can you send a screenshot of video not playing?

**Comment by KalpanaChetan** [comment]
![Screenshot (48).png](https://user-images.githubusercontent.com/112402936/211193120-39b512fb-b810-4016-acc3-b07efb2ee4c6.png)


![Screenshot (49).png](https://user-images.githubusercontent.com/112402936/211193134-11ca5be1-1039-4cb1-a395-2c8cb23b46db.png)


![Screenshot (47).png](https://user-images.githubusercontent.com/112402936/211193156-a2dd2057-f54c-40a8-98f7-451794caac72.png)


![Screenshot (50).png](https://user-images.githubusercontent.com/112402936/211193164-95cf6c6e-27e3-4df9-91b0-a9425709e2c0.png)

**Comment by prateekmedia** [comment]
It has IN for Indian region, scroll down

**Comment by KalpanaChetan** [comment]
Ok

**Comment by Quackdoc** [comment]
it's possibly related to https://github.com/TeamPiped/piped_dart/issues/11.
able to replicate.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [DioErrorType.other]: Deserializing '[title, My wife Was MURDERED, description, My wife Was MURDERED with Preston ...' to 'VideoInfo' failed due to: Deserializing '[{url: /watch?v=TYItqhOZ2E8, type: stream, title: ULTIMATE Try Not To LAUGH C...' to 'BuiltList<StreamItem>' failed due to: Deserializing '[url, /watch?v=DFP5LE7vVsQ&playnext=1&list=RDCMUC70Dib4MvFfT1tU6MqeyHpQ, type...' to 'StreamItem' failed due to: Tried to construct class "StreamItem" with null field "duration". This is forbidden; to allow it, mark "duration" with @nullable.
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:187:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#2      UnauthenticatedApi.streamInfo (package:piped_api/src/api/unauthenticated_api.dart:782:36)
<asynchronous suspension>
#3      PipedService.getVideoData (package:pstube/foundation/services/piped_service.dart:72:19)
<asynchronous suspension>
#4      VideosChangeNotifier.addVideoUrl (package:pstube/states/videos/videos_change_notifier.dart:33:23)
<asynchronous suspension>

Source stack:
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:187:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#2      UnauthenticatedApi.streamInfo (package:piped_api/src/api/unauthenticated_api.dart:782:36)
<asynchronous suspension>
#3      PipedService.getVideoData (package:pstube/foundation/services/piped_service.dart:72:19)
<asynchronous suspension>
#4      VideosChangeNotifier.addVideoUrl (package:pstube/states/videos/videos_change_notifier.dart:33:23)
<asynchronous suspension>

#0      UnauthenticatedApi.streamInfo (package:piped_api/src/api/unauthenticated_api.dart:788:7)
<asynchronous suspension>
#1      PipedService.getVideoData (package:pstube/foundation/services/piped_service.dart:72:19)
<asynchronous suspension>
#2      VideosChangeNotifier.addVideoUrl (package:pstube/states/videos/videos_change_notifier.dart:33:23)
<asynchronous suspension>
```

**Comment by Quackdoc** [comment]
a different error, but same symptoms

```
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [DioErrorType.other]: Deserializing '[title, Is Something Fishy With Mittens?, description, Hikaru reviews GM Benj...' to 'VideoInfo' failed due to: Deserializing '[{url: /watch?v=EYB7NOSY-hI, type: stream, title: Mittens The Chess Bot Will ...' to 'BuiltList<StreamItem>' failed due to: Deserializing '[url, /watch?v=6aCm7-G1v7I&playnext=1&list=RDCMUCweCc7bSMX5J4jEH7HFImng, type...' to 'StreamItem' failed due to: Tried to construct class "StreamItem" with null field "duration". This is forbidden; to allow it, mark "duration" with @nullable.
```
